### ISSUE TITLE
Creating Actors in Foundry version 12

### ISSUE THREAD

**Issue by Shortwise** [iconmaster5326/FoundryWildTalents#8]
Hello. Many thanks for creating Wild Talents for Foundry!

When I convert to Foundry version 12, it won't let me create actors. It flashes a warning but I am not certain what it says as it is long and does not stay visible very long. I just tried today. Then went back to my version 11 backup, which works fine.

**Comment by iconmaster5326** [comment]
That's not good! You can help me out a lot if you press F12 to bring up the developer console and see if you can see the warning message in the developer logs. Thanks for reporting this big issue!

**Comment by Shortwise** [comment]
foundry.js:631 Error: Actor validation errors:
  system: 
    silhouette: 
      0: 
        important: may not be undefined
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      1: 
        important: may not be undefined
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      2: 
        important: may not be undefined
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      3: 
        important: may not be undefined
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      4: 
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      5: 
        important: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
    at DataModelValidationFailure.asError (foundry-esm.js:4710:14)
    at Actor.validate (foundry-esm.js:10416:61)
    at new DataModel (foundry-esm.js:10165:12)
    at new BaseActor (foundry-esm.js:13216:7)
    at new ClientDocumentMixin (foundry.js:10516:7)
    at new Actor (foundry.js:15443:1)
    at #preCreateDocumentArray (foundry-esm.js:56313:17)
    at ClientDatabaseBackend._createDocuments (foundry-esm.js:56275:58)
    at ClientDatabaseBackend.create (foundry-esm.js:12264:19)
    at async Actor.createDocuments (foundry-esm.js:11407:23)

**Comment by Shortwise** [comment]
foundry.js:71791 Actor validation errors:
  system: 
    silhouette: 
      0: 
        important: may not be undefined
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      1: 
        important: may not be undefined
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      2: 
        important: may not be undefined
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      3: 
        important: may not be undefined
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      4: 
        brainBoxes: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined
      5: 
        important: may not be undefined
        shockDamage: may not be undefined
        killingDamage: may not be undefined

**Comment by Shortwise** [comment]
These are the two errors it produced while creating a character. Note I tested all of the other functions and they seem to be working correctly. I accidentally closed above, so I reopened issue. Ooops

**Comment by iconmaster5326** [comment]
Thanks for the error message! I've found it and fixed it in version 1.0.4. Cheers!
